// Banner config for United Real Estate — auto-generated by immersphere-production-orchestrator v0.4.0
window.BANNER_CONFIG = {
  clientName: "United Real Estate",
  slug: "united-real-estate",
  claim: "Experiencia inmobiliaria premium",
  logoUrl: "https://unitedrealestate.es/wp-content/uploads/united-logo-bl.png",
  heroImage: "https://fotos15.apinmo.com/6689/23276849/4-1.jpg",
  primaryColor: "#1a1a2e",
  accentColor: "#d4af37",
  waHref: "#contact",
};
