// Banner config for Sandhouse Inmobiliaria — auto-generated by immersphere-production-orchestrator v0.4.0
window.BANNER_CONFIG = {
  clientName: "Sandhouse Inmobiliaria",
  slug: "sandhouse-inmobiliaria",
  claim: "Experiencia inmobiliaria premium",
  logoUrl: "",
  heroImage: "",
  primaryColor: "#1a1a2e",
  accentColor: "#d4af37",
  waHref: "#contact",
};
