(function () {
  const items = [
    ['Ruta del atardecer','romantica','2h','calma','#f59e0b'],['Camino de calas secretas','naturaleza','4h','descubrimiento','#06b6d4'],['Tour gastronomico local','gastronomia','3h','sabroso','#ef4444'],['Paseo historico nocturno','cultura','2h','misterio','#6366f1'],
    ['Mirador de la ciudad','urbano','90m','panoramico','#0ea5e9'],['Experiencia wellness','wellness','3h','reset','#22c55e'],['Ruta familiar','familia','4h','facil','#facc15'],['Aventura activa','aventura','5h','energia','#f97316'],
    ['Arte y museos','cultura','3h','inspiracion','#a855f7'],['Mercado y tradicion','local','2h','autentico','#84cc16'],['Escapada romantica','romantica','24h','intimo','#ec4899'],['Naturaleza interpretativa','naturaleza','4h','aprendizaje','#10b981'],
    ['Ruta fotografica','creativa','3h','visual','#38bdf8'],['Plan premium 24h','premium','24h','lujo','#d4af37'],['Circuito en bici','aventura','3h','movimiento','#14b8a6'],['Experiencia de barrio','local','2h','cercano','#fb7185']
  ].map((row,index)=>({id:`route_${index+1}`,name:row[0],title:row[0],category:row[1],duration:row[2],mood:row[3],difficulty:index%4===0?'media':'facil',color:row[4],tags:[row[1],row[3]],price:'Demo',cta:{label:'Ver ruta',href:'#'},rewardType:row[1]==='premium'?'generic_cta':'route'}));
  const els=['stage','grid','phasePill','hostLine','rewardPanel','progress','question','microcopy','startBtn','secretBtn','noBtn','yesBtn','downloadBtn','resetBtn','toast'].reduce((a,id)=>(a[id]=document.getElementById(id),a),{});
  let deck=window.ZoltanSelectionEngine.createDeck(items).deck,session=null,phase='attract',revealItem=null,reward=null,lastPointer=0;
  function track(n,p){ if(window.ZoltanAnalytics) window.ZoltanAnalytics.track(n,Object.assign({module:'zoltan-travel-destiny-oracle'},p||{})); }
  function toast(t){ els.toast.textContent=t; els.toast.classList.add('on'); clearTimeout(toast.t); toast.t=setTimeout(()=>els.toast.classList.remove('on'),2200); }
  function setPhase(p){ phase=p; els.stage.classList.toggle('is-question',phase==='question'); updateCopy(); updateButtons(); render(); }
  function currentItems(){ return phase==='question'?window.ZoltanSelectionEngine.getQuestionGroup(session):phase==='reveal'&&revealItem?[revealItem]:deck; }
  function updateCopy(){ els.phasePill.textContent=phase.toUpperCase(); if(phase==='attract'){els.hostLine.textContent='No eliges destino. El destino te elige a ti.';els.progress.textContent='Brujula dormida';els.question.textContent='Piensa una ruta, plan o experiencia.';els.microcopy.textContent='La marca convierte una idea en itinerario accionable.';} if(phase==='pick'){els.hostLine.textContent='Piensa una. No la pulses. La brujula ya esta escuchando.';els.progress.textContent='Paso 1';els.question.textContent='Mira las experiencias y elige una en tu mente.';els.microcopy.textContent='Cuando la tengas, empieza la lectura.';} if(phase==='question'){els.hostLine.textContent='Izquierda NO. Derecha SI. Touch o botones.';els.progress.textContent=`Lectura ${session.currentBit+1} de ${session.maxBits}`;els.question.textContent='Tu experiencia aparece aqui?';els.microcopy.textContent='La brujula se esta cerrando.';} if(phase==='tension'){els.hostLine.textContent='Tu destino esta tomando forma.';els.progress.textContent='Ruta revelandose';els.question.textContent='La señal ya tiene direccion.';els.microcopy.textContent='El resultado acaba en accion, no en demo.';} if(phase==='reveal'){els.hostLine.textContent='El destino ha respondido.';els.progress.textContent='Ruta desbloqueada';els.question.textContent=`Tu ruta es: ${revealItem.name}`;els.microcopy.textContent='Guarda, copia o descarga tu tarjeta.';} }
  function updateButtons(){ els.startBtn.classList.toggle('hidden',phase!=='attract');els.secretBtn.classList.toggle('hidden',phase!=='pick');els.noBtn.disabled=phase!=='question';els.yesBtn.disabled=phase!=='question';els.downloadBtn.disabled=phase!=='reveal'; }
  function card(item){ const tilt=((item.index%5)-2)*1.2; return `<article class="card ${phase==='reveal'?'reveal':''}" style="--c:${item.color};--tilt:${tilt}deg"><div class="route">R${item.index+1}</div><div class="body"><strong>${item.name}</strong><span>${item.category} · ${item.duration}</span><small>${item.mood} · ${item.difficulty}</small></div></article>`; }
  function render(){ els.grid.innerHTML=currentItems().map(card).join(''); if(reward&&window.ZoltanRewardLayer){ window.ZoltanRewardLayer.renderRewardCard(els.rewardPanel,reward,{item:revealItem}); } else { els.rewardPanel.innerHTML='<span>Itinerario</span><strong>Aun no hay ruta.</strong><p>Completa la lectura para guardar una tarjeta accionable.</p>'; } }
  function start(){ session=window.ZoltanSelectionEngine.createSession(deck); revealItem=null; reward=null; if(window.ZoltanTelemetry) window.ZoltanTelemetry.startSession('zoltan-travel-destiny-oracle'); track('zoltan_travel_started'); setPhase('pick'); }
  function begin(){ session=window.ZoltanSelectionEngine.resetSession(session); setPhase('question'); }
  function answer(yes,source){ if(phase!=='question')return; if(window.ZoltanTelemetry) window.ZoltanTelemetry.recordInteraction('answer',{answer:yes?'yes':'no',source}); session=window.ZoltanSelectionEngine.answerCurrentQuestion(session,yes); track('zoltan_travel_answered',{answer:yes?'yes':'no'}); if(session.phase==='reveal'){ setPhase('tension'); setTimeout(reveal,750); } else render(),updateCopy(); }
  function reveal(){ const result=window.ZoltanSelectionEngine.getReveal(session); revealItem=result.ok?result.item:deck[0]; reward=window.ZoltanRewardLayer.createReward(revealItem,{type:revealItem.rewardType,title:`Tu ruta es: ${revealItem.name}`,subtitle:`Duracion ${revealItem.duration}. Mood ${revealItem.mood}.`,description:'Tarjeta local lista para guardar, copiar o descargar. QR real queda pendiente hasta generador local.',accentColor:revealItem.color,metadata:{module:'zoltan-travel-destiny-oracle',sector:'travel',selectedItemId:revealItem.id}}); if(window.ZoltanTelemetry) window.ZoltanTelemetry.endSession({revealed:true}); track('zoltan_travel_revealed',{item:revealItem.id}); setPhase('reveal'); toast('Ruta desbloqueada.'); }
  function download(){ if(reward) window.ZoltanRewardLayer.exportRewardPng(reward,{filename:`zoltan-travel-destiny-${Date.now()}.png`}); }
  function reset(){session=null;revealItem=null;reward=null;setPhase('attract');}
  els.startBtn.addEventListener('click',start);els.secretBtn.addEventListener('click',begin);els.yesBtn.addEventListener('click',()=>answer(true,'button'));els.noBtn.addEventListener('click',()=>answer(false,'button'));els.downloadBtn.addEventListener('click',download);els.resetBtn.addEventListener('click',reset);els.stage.addEventListener('pointerdown',(e)=>{if(phase!=='question'||Date.now()-lastPointer<650)return;lastPointer=Date.now();const r=els.stage.getBoundingClientRect();if(window.ZoltanTelemetry)window.ZoltanTelemetry.recordFallback(e.pointerType||'pointer-zone');answer(e.clientX-r.left>r.width/2,'zone');});
  window.__ZOLTAN_TRAVEL_QA__=()=>deck.map((item)=>{let s=window.ZoltanSelectionEngine.createSession(deck);for(let b=0;b<s.maxBits;b+=1)s=window.ZoltanSelectionEngine.answerCurrentQuestion(s,(item.binaryValue&(1<<b))!==0);const r=window.ZoltanSelectionEngine.getReveal(s);return{item:item.id,ok:r.ok&&r.item.id===item.id};});
  track('zoltan_travel_loaded');render();updateCopy();updateButtons();
})();
