export const costaInvestMotionBanner = {
  id: "dynamic-motion-banner-costa-invest",
  internalName: "Costa Invest · Experiencia Visual de Propiedad",
  client: { name: "Costa Invest", claim: "International property, local guidance", sector: "Inmobiliaria", location: "Playa Flamenca · Orihuela Costa", website: "https://costainvest.com/es/", email: "info@costainvest.com", phone: "+34 966 760 422", whatsapp: "+34 966 760 422", address: "Playa Flamenca, Orihuela Costa" },
  campaign: { type: "property_visit", name: "Experiencia visual de propiedad", headline: "DESCUBRE LA PROPIEDAD", subheadline: "Experiencia visual, QR y contacto directo para compradores internacionales en Orihuela Costa.", cta: "SOLICITA INFORMACIÓN", secondaryCta: "ESCANEA Y CONSULTA", supportLine: "Costa Invest · Playa Flamenca · Orihuela Costa", badges: ["Propiedad destacada", "Galería visual", "QR", "Consulta desde móvil", "Orihuela Costa"] },
  destination: { qrUrl: "https://aurum-properties-boutique.vercel.app/costa-invest", webPreviewUrl: "https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/costa-invest/", premiumDemoUrl: "https://aurum-properties-boutique.vercel.app/costa-invest", embeddableHtmlUrl: "https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/costa-invest/?embed=1" },
  assets: { logo: { url: "./assets/logo.svg", smartUrl: "./assets/logo-smart.svg", status: "public_candidate_pending_validation" }, images: [ { url: "./assets/property-1.jpg", source: "https://costainvest.com/", usage: "hero_media", status: "public_candidate_pending_validation" }, { url: "./assets/property-2.jpg", source: "https://costainvest.com/", usage: "hero_media", status: "public_candidate_pending_validation" }, { url: "./assets/property-3.jpg", source: "https://costainvest.com/", usage: "gallery_media", status: "public_candidate_pending_validation" } ] }
};
export default costaInvestMotionBanner;
