import {
  HandLandmarker,
  FilesetResolver,
} from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14";

const WASM_URL =
  "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm";
const MODEL_URL =
  "https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task";

const GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta";
const GEMINI_MODEL = "gemini-omni-flash-preview";
const STYLES = {
  movie3d:
    "Transform the person into a 3D animated movie character (stylized CGI " +
    "animation look, expressive big eyes, soft lighting).",
  anime:
    "Redraw the video as a hand-drawn anime with clean line art, cel " +
    "shading, and vibrant colors.",
  clay: "Transform the scene into claymation stop-motion with visible clay texture.",
  watercolor:
    "Repaint the video as a soft watercolor painting with loose brushwork.",
};
const PROMPT_SUFFIX =
  " This is a strict pixel-aligned edit of the source video: keep the same " +
  "pose, motion, timing, clothing colors, and background. The camera must " +
  "not change — no zoom, no crop, no recentering, and no change to the " +
  "field of view. The person's face and body must stay at exactly the same " +
  "position and size in the frame as the source: eyes, nose, and mouth must " +
  "remain at the same screen coordinates in every frame. Match the facial " +
  "expression exactly, frame by frame: preserve the exact degree of mouth " +
  "openness at every moment — if the mouth is slightly open and still, keep " +
  "it slightly open and still; do not close it, and do not add talking or " +
  "any mouth movement that is not in the source. Mirror blinks, gaze " +
  "direction, and eyebrow position at the same moments as the source. " +
  "Change only the visual style, nothing about the geometry, composition, " +
  "or performance.";

const WRIST = 0, THUMB_TIP = 4, INDEX_TIP = 8, MIDDLE_MCP = 9;

// Tracking constants — same audited pipeline as the live web app.
const MAX_LOST_FRAMES = 25;
const JUMP_CONFIRM_FRAMES = 2;

const orig = document.getElementById("orig");
const sty = document.getElementById("sty");
const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");
const statusEl = document.getElementById("status");
const stage = document.getElementById("stage");
const drop = document.getElementById("drop");
const btnGenerate = document.getElementById("btn-generate");
const btnPlaceholder = document.getElementById("btn-placeholder");
const btnPlay = document.getElementById("btn-play");
const btnExport = document.getElementById("btn-export");
const portalFileInput = document.getElementById("portal-file");
const logoFileInput = document.getElementById("logo-file");
const clearPortalBtn = document.getElementById("btn-clear-portal");
const headlineInput = document.getElementById("headline-input");
const ctaInput = document.getElementById("cta-input");
const brandInput = document.getElementById("brand-input");
const landingInput = document.getElementById("landing-input");
const frameExpandInput = document.getElementById("frame-expand");
const portalScaleInput = document.getElementById("portal-scale");
const portalOffsetXInput = document.getElementById("portal-offset-x");
const portalOffsetYInput = document.getElementById("portal-offset-y");
const portalGlowInput = document.getElementById("portal-glow");
const outsideDimInput = document.getElementById("outside-dim");
const frameExpandValue = document.getElementById("frame-expand-value");
const portalScaleValue = document.getElementById("portal-scale-value");
const portalOffsetXValue = document.getElementById("portal-offset-x-value");
const portalOffsetYValue = document.getElementById("portal-offset-y-value");
const portalGlowValue = document.getElementById("portal-glow-value");
const outsideDimValue = document.getElementById("outside-dim-value");

let landmarker = null;
let videoFile = null;
let haveAI = false;        // stylized video generated by Gemini
let usePlaceholder = false; // local hue-shift stand-in for keyless MIRRORA testing
let corners = null;
let presence = 0;
let frameActive = false;
let lostFrames = 0;
let jumpFrames = 0;
let recorder = null;
let exporting = false;
let portalUrl = null;
let portalElement = null;
let portalType = "none";
let logoUrl = null;
let logoImage = null;

function status(msg) {
  statusEl.textContent = msg;
  // Messages ending in an ellipsis are in-progress — show the spinner.
  statusEl.classList.toggle("working", msg.trim().endsWith("..."));
}

function revokePortalUrl() {
  if (portalUrl) URL.revokeObjectURL(portalUrl);
  portalUrl = null;
  portalElement = null;
  portalType = "none";
}

function revokeLogoUrl() {
  if (logoUrl) URL.revokeObjectURL(logoUrl);
  logoUrl = null;
  logoImage = null;
}

function syncRangeLabels() {
  frameExpandValue.textContent = `${frameExpandInput.value}%`;
  portalScaleValue.textContent = `${portalScaleInput.value}%`;
  portalOffsetXValue.textContent = portalOffsetXInput.value;
  portalOffsetYValue.textContent = portalOffsetYInput.value;
  portalGlowValue.textContent = `${portalGlowInput.value}%`;
  outsideDimValue.textContent = `${outsideDimInput.value}%`;
}

function readComposer() {
  return {
    headline: headlineInput.value.trim(),
    cta: ctaInput.value.trim(),
    brand: brandInput.value.trim(),
    landing: landingInput.value.trim(),
    frameExpand: Number(frameExpandInput.value) / 100,
    portalScale: Number(portalScaleInput.value) / 100,
    portalOffsetX: Number(portalOffsetXInput.value) / 100,
    portalOffsetY: Number(portalOffsetYInput.value) / 100,
    portalGlow: Number(portalGlowInput.value) / 100,
    outsideDim: Number(outsideDimInput.value) / 100,
  };
}

function loadPortalContent(file) {
  revokePortalUrl();
  if (!file) return;
  portalUrl = URL.createObjectURL(file);
  if (file.type.startsWith("video/")) {
    const video = document.createElement("video");
    video.src = portalUrl;
    video.muted = true;
    video.loop = true;
    video.playsInline = true;
    video.crossOrigin = "anonymous";
    portalElement = video;
    portalType = "video";
    video.addEventListener("loadedmetadata", () => status(`Contenido portal listo: ${file.name}`), { once: true });
  } else {
    const img = new Image();
    img.onload = () => status(`Imagen portal lista: ${file.name}`);
    img.src = portalUrl;
    portalElement = img;
    portalType = "image";
  }
}

function loadLogo(file) {
  revokeLogoUrl();
  if (!file) return;
  logoUrl = URL.createObjectURL(file);
  logoImage = new Image();
  logoImage.onload = () => status(`Logo listo: ${file.name}`);
  logoImage.src = logoUrl;
}

// ---- key + style panel ----
const keyInput = document.getElementById("gem-key");
const keyRemember = document.getElementById("gem-remember");
const styleSelect = document.getElementById("style-select");
const styleCustom = document.getElementById("style-custom");

keyInput.value =
  localStorage.getItem("gemini-key") || sessionStorage.getItem("gemini-key") || "";
keyRemember.checked = !!localStorage.getItem("gemini-key");
styleSelect.value = localStorage.getItem("ai-style") || "movie3d";
styleCustom.value = localStorage.getItem("ai-style-custom") || "";
styleCustom.classList.toggle("hidden", styleSelect.value !== "custom");
styleSelect.addEventListener("change", () => {
  styleCustom.classList.toggle("hidden", styleSelect.value !== "custom");
  localStorage.setItem("ai-style", styleSelect.value);
});
styleCustom.addEventListener("change", () =>
  localStorage.setItem("ai-style-custom", styleCustom.value)
);
portalFileInput.addEventListener("change", (e) => loadPortalContent(e.target.files[0]));
logoFileInput.addEventListener("change", (e) => loadLogo(e.target.files[0]));
clearPortalBtn.addEventListener("click", () => {
  revokePortalUrl();
  revokeLogoUrl();
  portalFileInput.value = "";
  logoFileInput.value = "";
  status("Portal personalizado limpiado. Se usara el modo demo local.");
});
[
  frameExpandInput,
  portalScaleInput,
  portalOffsetXInput,
  portalOffsetYInput,
  portalGlowInput,
  outsideDimInput,
].forEach((input) => {
  input.addEventListener("input", syncRangeLabels);
});
syncRangeLabels();
function saveKey() {
  const key = keyInput.value.trim();
  localStorage.removeItem("gemini-key");
  sessionStorage.removeItem("gemini-key");
  if (key) (keyRemember.checked ? localStorage : sessionStorage).setItem("gemini-key", key);
  return key;
}
function prompt() {
  const style =
    styleSelect.value === "custom" && styleCustom.value.trim()
      ? styleCustom.value.trim()
      : STYLES[styleSelect.value] || STYLES.movie3d;
  return style + PROMPT_SUFFIX;
}

// ---- video loading ----
document.getElementById("file").addEventListener("change", (e) => {
  if (e.target.files[0]) loadVideo(e.target.files[0]);
});
drop.addEventListener("dragover", (e) => {
  e.preventDefault();
  drop.classList.add("over");
});
drop.addEventListener("dragleave", () => drop.classList.remove("over"));
drop.addEventListener("drop", (e) => {
  e.preventDefault();
  drop.classList.remove("over");
  if (e.dataTransfer.files[0]) loadVideo(e.dataTransfer.files[0]);
});

async function loadVideo(file) {
  videoFile = file;
  haveAI = false;
  usePlaceholder = false;
  btnPlay.disabled = true;
  btnExport.disabled = true;
  orig.src = URL.createObjectURL(file);
  await new Promise((res) => (orig.onloadedmetadata = res));
  canvas.width = orig.videoWidth;
  canvas.height = orig.videoHeight;
  stage.style.display = "flex";
  drop.classList.add("compact");
  drawPoster();
  status(
    `Loaded ${file.name} (${orig.videoWidth}×${orig.videoHeight}, ` +
    `${orig.duration.toFixed(1)}s). Generate the AI video, or test with the placeholder.`
  );
  if (!landmarker) initLandmarker();
}

function drawPoster() {
  orig.currentTime = 0.01;
  orig.onseeked = () => {
    ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);
    orig.onseeked = null;
  };
}

async function initLandmarker() {
  status("Loading hand tracker…");
  const fileset = await FilesetResolver.forVisionTasks(WASM_URL);
  landmarker = await HandLandmarker.createFromOptions(fileset, {
    baseOptions: { modelAssetPath: MODEL_URL, delegate: "GPU" },
    runningMode: "VIDEO",
    numHands: 2,
    minHandDetectionConfidence: 0.3,
    minHandPresenceConfidence: 0.3,
    minTrackingConfidence: 0.3,
  });
  status("Tracking de manos listo.");
}

// Dev hook: render one frame at time t (seconds) without realtime playback —
// lets automated tests drive the pipeline in environments that suspend media.
window.__step = (t) =>
  new Promise((resolve) => {
    orig.onseeked = () => {
      orig.onseeked = null;
      ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);
      const res = landmarker.detectForVideo(orig, performance.now());
      updateTracker(res.landmarks || []);
      if (corners && presence > 0.01) {
        drawWindow(corners);
        drawOutline(corners, t);
      }
      resolve({
        presence: +presence.toFixed(2),
        corners: corners
          ? corners.map((p) => [Math.round(p.x), Math.round(p.y)])
          : null,
      });
    };
    orig.currentTime = t;
  });

// Dev convenience: ?src=file.mov loads a local file from the dev server.
const srcParam = new URLSearchParams(location.search).get("src");
if (srcParam) {
  fetch(srcParam)
    .then((r) => r.blob())
    .then((b) => loadVideo(new File([b], srcParam, { type: "video/quicktime" })));
}

// ---- AI generation (Gemini Omni Flash video editing, BYOK) ----

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function fileToBase64(file) {
  return new Promise((resolve, reject) => {
    const fr = new FileReader();
    fr.onload = () => resolve(fr.result.split(",")[1]);
    fr.onerror = reject;
    fr.readAsDataURL(file);
  });
}

async function gemFetch(key, path, init = {}) {
  const res = await fetch(`${GEMINI_BASE}/${path}`, {
    ...init,
    headers: {
      "x-goog-api-key": key,
      ...(init.body ? { "Content-Type": "application/json" } : {}),
      ...(init.headers || {}),
    },
  });
  if (!res.ok) {
    let detail = res.statusText;
    try {
      detail = (await res.json())?.error?.message || detail;
    } catch {}
    throw new Error(`${res.status}: ${detail.slice(0, 160)}`);
  }
  return res.json();
}

// The Interactions API is in preview; be liberal about where the output
// video and status live in the response. Verified live shape: the video is
// in steps[].content[] on the step with type "model_output".
function findOutputVideo(inter) {
  if (inter.output_video) return inter.output_video;
  if (inter.outputVideo) return inter.outputVideo;
  const lists = [inter.outputs, inter.output, inter.content].filter(Array.isArray);
  for (const step of inter.steps || []) {
    if (Array.isArray(step.content)) lists.push(step.content);
  }
  for (const list of lists) {
    const v = list.find(
      (o) => o?.type?.includes?.("video") || o?.video || o?.mime_type?.startsWith?.("video")
    );
    if (v) return v.video || v;
  }
  return null;
}

function isPending(inter) {
  const s = (inter.status || inter.state || "").toLowerCase();
  return ["pending", "in_progress", "processing", "running", "queued"].some((k) =>
    s.includes(k)
  );
}

btnGenerate.addEventListener("click", async () => {
  const key = saveKey();
  if (!key) {
    status("Anade tu clave Gemini arriba o usa el modo demo local.");
    keyInput.focus();
    return;
  }
  if (!videoFile) return;
  if (videoFile.size > 15 * 1024 * 1024) {
    status("⚠️ Keep the video under ~15MB (a few seconds of 720p) for inline upload.");
    return;
  }
  btnGenerate.disabled = true;
  try {
    status("Encoding video…");
    const b64 = await fileToBase64(videoFile);

    status("Submitting to Gemini Omni Flash — this can take a few minutes…");
    let inter = await gemFetch(key, "interactions", {
      method: "POST",
      body: JSON.stringify({
        model: GEMINI_MODEL,
        input: [
          {
            type: "video",
            mime_type: videoFile.type || "video/mp4",
            data: b64,
          },
          { type: "text", text: prompt() },
        ],
      }),
    });
    console.log("interaction response:", inter);

    // Poll the interaction until it settles, if it reports as in-progress.
    const id = inter.id || inter.name;
    let waited = 0;
    while (isPending(inter) && waited < 600) {
      await sleep(5000);
      waited += 5;
      inter = await gemFetch(key, `interactions/${id}`);
      status(`Generating… (${waited}s, status: ${inter.status || inter.state || "working"})`);
    }

    const vid = findOutputVideo(inter);
    if (!vid) {
      console.error("full response:", inter);
      throw new Error("no video in response — see console for the raw payload");
    }

    let blob;
    if (vid.data) {
      const bytes = Uint8Array.from(atob(vid.data), (c) => c.charCodeAt(0));
      blob = new Blob([bytes], { type: vid.mime_type || "video/mp4" });
    } else {
      // uri delivery: wait for the file to become ACTIVE, then download.
      let uri = vid.uri || vid.file_uri || vid.url;
      if (!uri) throw new Error("no video data or uri in response");
      const fileName = uri.includes("/files/")
        ? "files/" + uri.split("/files/")[1].split(/[?#]/)[0]
        : uri;
      if (!/^https?:/.test(uri)) uri = `${GEMINI_BASE}/${fileName}:download?alt=media`;
      for (let i = 0; i < 60; i++) {
        const f = await gemFetch(key, fileName);
        if ((f.state || "").includes("ACTIVE")) break;
        status(`Waiting for the output file… (${(f.state || "processing").toLowerCase()})`);
        await sleep(5000);
      }
      status("Downloading result…");
      const res = await fetch(uri, { headers: { "x-goog-api-key": key } });
      if (!res.ok) throw new Error(`download failed: ${res.status}`);
      blob = await res.blob();
    }

    sty.src = URL.createObjectURL(blob);
    await new Promise((res) => (sty.onloadedmetadata = res));
    haveAI = true;
    usePlaceholder = false;
    btnPlay.disabled = false;
    btnExport.disabled = false;
    status("AI video ready — preview or export.");
  } catch (err) {
    console.error(err);
    status("⚠️ Generation failed: " + (err.message || err));
  } finally {
    btnGenerate.disabled = false;
  }
});

btnPlaceholder.addEventListener("click", () => {
  if (!videoFile) return;
  usePlaceholder = true;
  haveAI = false;
  btnPlay.disabled = false;
  btnExport.disabled = false;
  status("Placeholder style active (hue shift) — preview or export, no key needed.");
});

// ---- tracking (ported from finger-frame-effect main.js) ----
function toPixel(lm) {
  return { x: lm.x * canvas.width, y: lm.y * canvas.height };
}
function dist(a, b) {
  return Math.hypot(a.x - b.x, a.y - b.y);
}
function lerpPt(a, b, t) {
  return { x: a.x + (b.x - a.x) * t, y: a.y + (b.y - a.y) * t };
}
function polygonArea(pts) {
  let a = 0;
  for (let i = 0; i < pts.length; i++) {
    const p = pts[i], q = pts[(i + 1) % pts.length];
    a += p.x * q.y - q.x * p.y;
  }
  return Math.abs(a / 2);
}

function computeQuad(hands) {
  if (hands.length !== 2) return null;
  const info = hands.map((lm) => ({
    index: toPixel(lm[INDEX_TIP]),
    thumb: toPixel(lm[THUMB_TIP]),
    wristX: toPixel(lm[WRIST]).x,
    scale: dist(toPixel(lm[WRIST]), toPixel(lm[MIDDLE_MCP])) + 1,
  }));
  const needed = frameActive ? 0.2 : 0.75;
  for (const hd of info) {
    if (dist(hd.thumb, hd.index) < hd.scale * needed) return null;
  }
  info.sort((a, b) => a.wristX - b.wristX);
  const [A, B] = info;
  const pts = [A.index, B.index, B.thumb, A.thumb];
  const cx = pts.reduce((s, p) => s + p.x, 0) / 4;
  const cy = pts.reduce((s, p) => s + p.y, 0) / 4;
  const hull = [...pts].sort(
    (a, b) => Math.atan2(a.y - cy, a.x - cx) - Math.atan2(b.y - cy, b.x - cx)
  );
  const minArea = frameActive ? 0.0005 : 0.005;
  if (polygonArea(hull) < canvas.width * canvas.height * minArea) return null;
  return pts;
}

function updateTracker(hands) {
  const target = computeQuad(hands);
  if (target) {
    if (!corners) {
      lostFrames = 0;
      frameActive = true;
      jumpFrames = 0;
      corners = target;
      presence = Math.min(1, presence + 0.12);
    } else {
      const moved = target.reduce((s, p, i) => s + dist(p, corners[i]), 0) / 4;
      if (moved > canvas.width * 0.3 && ++jumpFrames < JUMP_CONFIRM_FRAMES) {
        if (++lostFrames > MAX_LOST_FRAMES) presence = Math.max(0, presence - 0.05);
      } else {
        lostFrames = 0;
        frameActive = true;
        jumpFrames = 0;
        const alpha = Math.min(0.85, Math.max(0.35, moved / (canvas.width * 0.05)));
        corners = corners.map((c, i) => lerpPt(c, target[i], alpha));
        presence = Math.min(1, presence + 0.12);
      }
    }
  } else if (corners && ++lostFrames <= MAX_LOST_FRAMES) {
    presence = Math.min(1, presence + 0.12);
  } else {
    presence = Math.max(0, presence - 0.05);
    if (presence === 0) {
      corners = null;
      frameActive = false;
      jumpFrames = 0;
    }
  }
}

// ---- rendering ----
function quadPath(q) {
  ctx.beginPath();
  ctx.moveTo(q[0].x, q[0].y);
  for (let i = 1; i < 4; i++) ctx.lineTo(q[i].x, q[i].y);
  ctx.closePath();
}

function resetTrackingState() {
  corners = null;
  presence = 0;
  frameActive = false;
  lostFrames = 0;
  jumpFrames = 0;
  lastVideoTime = -1;
}

function expandQuad(q, amount) {
  const cx = q.reduce((sum, p) => sum + p.x, 0) / q.length;
  const cy = q.reduce((sum, p) => sum + p.y, 0) / q.length;
  const factor = Math.max(0.35, 1 + amount);
  return q.map((p) => ({
    x: cx + (p.x - cx) * factor,
    y: cy + (p.y - cy) * factor,
  }));
}

function quadBounds(q) {
  const xs = q.map((p) => p.x);
  const ys = q.map((p) => p.y);
  const minX = Math.min(...xs);
  const maxX = Math.max(...xs);
  const minY = Math.min(...ys);
  const maxY = Math.max(...ys);
  return { x: minX, y: minY, width: maxX - minX, height: maxY - minY };
}

function drawOutsideDim(q, alpha) {
  if (alpha <= 0) return;
  ctx.save();
  ctx.globalAlpha = presence * alpha;
  ctx.fillStyle = "#000";
  ctx.beginPath();
  ctx.rect(0, 0, canvas.width, canvas.height);
  ctx.moveTo(q[0].x, q[0].y);
  for (let i = 3; i >= 0; i--) ctx.lineTo(q[i].x, q[i].y);
  ctx.closePath();
  ctx.fill("evenodd");
  ctx.restore();
}

function drawCoverSource(source, bounds, scale = 1, offsetX = 0, offsetY = 0) {
  const sourceWidth = source.videoWidth || source.naturalWidth || source.width;
  const sourceHeight = source.videoHeight || source.naturalHeight || source.height;
  if (!sourceWidth || !sourceHeight || !bounds.width || !bounds.height) return false;
  const coverScale = Math.max(bounds.width / sourceWidth, bounds.height / sourceHeight) * scale;
  const drawWidth = sourceWidth * coverScale;
  const drawHeight = sourceHeight * coverScale;
  const x = bounds.x + (bounds.width - drawWidth) / 2 + offsetX * bounds.width;
  const y = bounds.y + (bounds.height - drawHeight) / 2 + offsetY * bounds.height;
  ctx.drawImage(source, x, y, drawWidth, drawHeight);
  return true;
}

function drawWindow(q) {
  const composer = readComposer();
  const expanded = expandQuad(q, composer.frameExpand);
  const bounds = quadBounds(expanded);
  drawOutsideDim(expanded, composer.outsideDim);
  ctx.save();
  quadPath(expanded);
  ctx.clip();
  ctx.globalAlpha = presence;
  if (portalElement && (portalType === "image" || portalElement.readyState >= 2)) {
    drawCoverSource(portalElement, bounds, composer.portalScale, composer.portalOffsetX, composer.portalOffsetY);
  } else if (haveAI) {
    ctx.drawImage(sty, 0, 0, canvas.width, canvas.height);
  } else {
    ctx.filter = "hue-rotate(140deg) saturate(1.7) contrast(1.15)";
    ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);
    ctx.filter = "none";
  }
  ctx.restore();
  ctx.globalAlpha = 1;
  return expanded;
}

function drawOutline(q, t, glow = 0.55) {
  ctx.save();
  ctx.globalAlpha = presence;
  if (glow > 0) {
    quadPath(q);
    ctx.setLineDash([]);
    ctx.lineWidth = Math.max(6, canvas.width * 0.006) * glow;
    ctx.strokeStyle = "rgba(255, 194, 75, 0.8)";
    ctx.shadowColor = "rgba(255, 107, 94, 0.75)";
    ctx.shadowBlur = Math.max(16, canvas.width * 0.018) * glow;
    ctx.stroke();
  }
  quadPath(q);
  ctx.setLineDash([10, 8]);
  ctx.lineDashOffset = -t * 40;
  ctx.lineWidth = Math.max(2, canvas.width * 0.002);
  ctx.strokeStyle = "rgba(255,255,255,0.95)";
  ctx.shadowColor = "rgba(0,0,0,0.5)";
  ctx.shadowBlur = 6;
  ctx.stroke();
  ctx.setLineDash([]);
  ctx.lineDashOffset = 0;
  ctx.shadowBlur = 0;
  q.forEach((p, i) => {
    const r = 7 + Math.sin(t * 3 + i * 1.5) * 1.5;
    const halo = (t * 0.8 + i * 0.25) % 1;
    ctx.beginPath();
    ctx.arc(p.x, p.y, r + halo * 14, 0, Math.PI * 2);
    ctx.strokeStyle = `rgba(255,255,255,${0.5 * (1 - halo) * presence})`;
    ctx.lineWidth = 2;
    ctx.stroke();
    ctx.beginPath();
    ctx.arc(p.x, p.y, r, 0, Math.PI * 2);
    ctx.fillStyle = "#fff";
    ctx.fill();
    ctx.beginPath();
    ctx.arc(p.x, p.y, r, 0, Math.PI * 2);
    ctx.strokeStyle = "rgba(0,0,0,0.25)";
    ctx.lineWidth = 1.5;
    ctx.stroke();
  });
  ctx.restore();
}

function drawRoundRect(x, y, width, height, radius) {
  const r = Math.min(radius, width / 2, height / 2);
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + width, y, x + width, y + height, r);
  ctx.arcTo(x + width, y + height, x, y + height, r);
  ctx.arcTo(x, y + height, x, y, r);
  ctx.arcTo(x, y, x + width, y, r);
  ctx.closePath();
}

function drawCommercialOverlay() {
  const composer = readComposer();
  const margin = Math.max(28, canvas.width * 0.028);
  const panelHeight = Math.max(190, canvas.height * 0.19);
  const panelY = canvas.height - panelHeight - margin;

  ctx.save();
  ctx.globalAlpha = 0.92;
  drawRoundRect(margin, panelY, canvas.width - margin * 2, panelHeight, 34);
  ctx.fillStyle = "rgba(8, 8, 12, 0.72)";
  ctx.fill();
  ctx.strokeStyle = "rgba(255,255,255,0.18)";
  ctx.lineWidth = Math.max(2, canvas.width * 0.0015);
  ctx.stroke();

  const brandSize = Math.max(20, canvas.width * 0.012);
  const titleSize = Math.max(34, canvas.width * 0.025);
  const ctaSize = Math.max(22, canvas.width * 0.016);
  const textX = margin * 1.65;
  let textY = panelY + panelHeight * 0.24;

  ctx.globalAlpha = 1;
  ctx.fillStyle = "rgba(255,255,255,0.72)";
  ctx.font = `800 ${brandSize}px system-ui, sans-serif`;
  ctx.fillText(composer.brand || "MIRRORA", textX, textY);

  textY += titleSize * 1.18;
  ctx.fillStyle = "#ffffff";
  ctx.font = `850 ${titleSize}px system-ui, sans-serif`;
  const maxTitleWidth = canvas.width - textX - margin * 3.2;
  const title = composer.headline || "Tu experiencia empieza aqui";
  const titleText = ctx.measureText(title).width > maxTitleWidth
    ? `${title.slice(0, 42).trim()}...`
    : title;
  ctx.fillText(titleText, textX, textY);

  const ctaText = composer.landing ? `${composer.cta || "Continuar"} · ${composer.landing}` : (composer.cta || "Continuar");
  const ctaWidth = Math.min(canvas.width - textX - margin * 2, ctx.measureText(ctaText).width + ctaSize * 1.8);
  const ctaHeight = ctaSize * 1.85;
  const ctaY = panelY + panelHeight - ctaHeight - panelHeight * 0.16;
  drawRoundRect(textX, ctaY, ctaWidth, ctaHeight, ctaHeight / 2);
  ctx.fillStyle = "rgba(255, 194, 75, 0.94)";
  ctx.fill();
  ctx.fillStyle = "#1a120b";
  ctx.font = `850 ${ctaSize}px system-ui, sans-serif`;
  ctx.fillText(ctaText, textX + ctaSize * 0.8, ctaY + ctaSize * 1.22);

  if (logoImage?.complete && logoImage.naturalWidth) {
    const logoMaxW = canvas.width * 0.16;
    const logoMaxH = panelHeight * 0.46;
    const scale = Math.min(logoMaxW / logoImage.naturalWidth, logoMaxH / logoImage.naturalHeight, 1);
    const logoW = logoImage.naturalWidth * scale;
    const logoH = logoImage.naturalHeight * scale;
    ctx.drawImage(logoImage, canvas.width - margin * 1.65 - logoW, panelY + panelHeight * 0.24, logoW, logoH);
  }
  ctx.restore();
}

let lastVideoTime = -1;
function loop() {
  if (!orig.paused && !orig.ended) requestAnimationFrame(loop);

  ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);

  if (landmarker && orig.currentTime !== lastVideoTime) {
    lastVideoTime = orig.currentTime;
    const res = landmarker.detectForVideo(orig, performance.now());
    updateTracker(res.landmarks || []);
  }

  // Keep the stylized video in step with the original.
  if (haveAI && Math.abs(sty.currentTime - orig.currentTime) > 0.15) {
    sty.currentTime = orig.currentTime;
  }
  if (portalType === "video" && portalElement && portalElement.readyState >= 2) {
    if (portalElement.paused && !orig.paused) portalElement.play().catch(() => {});
    if (portalElement.duration && portalElement.currentTime >= portalElement.duration - 0.08) {
      portalElement.currentTime = 0;
    }
  }

  if (corners && presence > 0.01) {
    const composer = readComposer();
    const visibleQuad = drawWindow(corners);
    drawOutline(visibleQuad || corners, orig.currentTime, composer.portalGlow);
  }
  drawCommercialOverlay();
}

function seekVideo(video, time) {
  return new Promise((resolve) => {
    if (!Number.isFinite(video.duration) || Math.abs(video.currentTime - time) < 0.02) {
      resolve();
      return;
    }
    const done = () => resolve();
    video.addEventListener("seeked", done, { once: true });
    video.currentTime = time;
  });
}

async function resetPlayback() {
  orig.pause();
  sty.pause();
  if (portalType === "video" && portalElement) portalElement.pause();
  resetTrackingState();
  await seekVideo(orig, 0);
  if (haveAI) await seekVideo(sty, 0);
  if (portalType === "video" && portalElement) await seekVideo(portalElement, 0);
  ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);
  drawCommercialOverlay();
}

async function playThrough() {
  await resetPlayback();
  if (haveAI) {
    await sty.play();
  }
  if (portalType === "video" && portalElement) {
    await portalElement.play().catch(() => {});
  }
  await orig.play();
  requestAnimationFrame(loop);
}

btnPlay.addEventListener("click", () => {
  if (exporting) return;
  playThrough();
  status("Previewing…");
});

// ---- export (canvas capture -> webm download) ----
btnExport.addEventListener("click", async () => {
  if (exporting) return;
  exporting = true;
  btnExport.disabled = true;
  btnPlay.disabled = true;
  status("Exporting — playing the video through once…");

  await resetPlayback();
  const stream = canvas.captureStream(30);
  // Prefer MP4 where the browser can record it (Safari, newer Chrome);
  // fall back to WebM elsewhere.
  const mime = [
    "video/mp4;codecs=avc1.42E01E",
    "video/mp4",
    "video/webm;codecs=vp9",
    "video/webm",
  ].find((m) => MediaRecorder.isTypeSupported(m)) || "video/webm";
  const isMp4 = mime.startsWith("video/mp4");
  recorder = new MediaRecorder(stream, {
    mimeType: mime,
    videoBitsPerSecond: 10_000_000,
  });
  const chunks = [];
  recorder.ondataavailable = (e) => e.data.size && chunks.push(e.data);
  let exportTimer = null;
  const stopRecorder = () => {
    if (exportTimer) clearTimeout(exportTimer);
    orig.removeEventListener("ended", stopRecorder);
    if (recorder?.state === "recording") {
      recorder.requestData?.();
      recorder.stop();
    }
  };
  recorder.onstop = () => {
    stream.getTracks().forEach((track) => track.stop());
    if (portalType === "video" && portalElement) portalElement.pause();
    const ext = isMp4 ? "mp4" : "webm";
    const blob = new Blob(chunks, { type: isMp4 ? "video/mp4" : "video/webm" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `mirrora-finger-frame-portal.${ext}`;
    a.click();
    status(
      `Exportado mirrora-finger-frame-portal.${ext}.` +
      (isMp4
        ? ""
        : " (Este navegador graba WebM; puedes convertirlo con ffmpeg si necesitas MP4.)")
    );
    exporting = false;
    btnExport.disabled = false;
    btnPlay.disabled = false;
  };

  orig.addEventListener("ended", stopRecorder, { once: true });
  const durationMs = Number.isFinite(orig.duration) ? (orig.duration + 0.75) * 1000 : 30000;
  exportTimer = setTimeout(stopRecorder, durationMs);
  recorder.start();
  if (haveAI) await sty.play();
  if (portalType === "video" && portalElement) await portalElement.play().catch(() => {});
  await orig.play();
  requestAnimationFrame(loop);
});

window.addEventListener("beforeunload", () => {
  revokePortalUrl();
  revokeLogoUrl();
});
